Create sign up page
fcodelabs/training-web-angular pull request #43
Opened 2023-01-20 13:52 UTC by Nuwa-Hub

[ITP-1395]
[ITP-1391]

2023-01-23 02:48 UTC, ChamaraWee commented
Add a screenshot of developed comp

2023-01-23 02:49 UTC, ChamaraWee commented
Use kendo UI as comp library.

2023-01-24 15:01 UTC, ChamaraWee requested changes

2023-01-24 15:01 UTC, ChamaraWee commented on src/app/containers/sign-in/sign-in.component.ts
> +  username: string;
- username: string = '' 
- username!: string  
- username: string | undefined
 you can use any of these use according to the use case.

2023-01-24 15:01 UTC, ChamaraWee commented on src/app/containers/sign-in/sign-in.component.html
> +              (change)="handleChange(userInput.value)"
it's better to use from control to do this. cause you might have to use form control in the actual project.

2023-01-24 15:01 UTC, ChamaraWee commented on src/app/containers/sign-in/sign-in.component.ts
> +  handleChange(value: string) {
use form control for input data handling

2023-01-27 05:24 UTC, Nuwa-Hub commented on src/app/containers/sign-in/sign-in.component.html
> +              (change)="handleChange(userInput.value)"
add form group

2023-01-27 12:07 UTC, ChamaraWee approved these changes

2023-01-27 12:12 UTC, ChamaraWee requested changes

2023-01-27 12:12 UTC, ChamaraWee commented on src/app/containers/sign-in/sign-in.component.ts
> +  username = new FormControl('');
since we have only one input form Control is enough. You don't have to use both. refer to this PR.

2023-01-29 08:30 UTC, ChamaraWee commented on src/app/containers/sign-in/sign-in.component.ts
> +    "https://firebasestorage.googleapis.com/v0/b/dailydiary-96e2f.appspot.com/o/rose-flower-icon-vector-3720361.jpg?alt=media&token=6633787a-d348-4287-a29a-0e251002f1e0";
bad practice. Move this to env.

2023-01-29 08:59 UTC, ChamaraWee approved these changes

2023-01-29 09:10 UTC, merged