Create home page UI
fcodelabs/training-web-angular pull request #44
Opened 2023-01-22 10:36 UTC by Nuwa-Hub

[ITP-1371]

2023-01-23 02:55 UTC, ChamaraWee commented
Add a screenshot please.

2023-01-24 15:02 UTC, ChamaraWee requested changes

2023-01-24 15:02 UTC, ChamaraWee commented on src/app/app.component.scss
> +}
wrong indentation?

2023-01-24 15:02 UTC, ChamaraWee commented on src/app/app.module.ts
> +
spaces ??

2023-01-24 15:02 UTC, ChamaraWee commented on src/app/components/card-form/card-form.component.ts
> +    this.title = '';
use form group here this where you should use form group because there's multiple form control that required the validation.

2023-01-24 15:02 UTC, ChamaraWee commented on src/app/components/card-list/card-list.component.scss
> +margin: 0%;
- wrong indentation. 

- padding 0 is work don't have to specify the `%`. btw why are you using padding 0 here.is there any padding coming from parent?

2023-01-25 20:53 UTC, Nuwa-Hub commented on src/app/app.component.scss
> +}
done

2023-01-25 20:53 UTC, Nuwa-Hub commented on src/app/components/card-form/card-form.component.ts
> +    this.title = '';
done

2023-01-25 20:53 UTC, Nuwa-Hub commented on src/app/components/card-list/card-list.component.scss
> +margin: 0%;
remove them

2023-01-31 04:41 UTC, ChamaraWee commented on src/app/components/card-form/card-form.component.ts
> +      this.addCardForm.value.description === "" ||
`this.addCardForm.valid` will do the work

2023-01-31 04:43 UTC, ChamaraWee requested changes

2023-01-31 04:43 UTC, ChamaraWee commented on src/app/components/card-form/card-form.component.ts
> +      if (this.username !== undefined) {
what will happen if username is null of empty string.

2023-01-31 04:43 UTC, ChamaraWee commented on src/app/components/card-form/card-form.component.ts
> +        this.addCardForm.value.description == "";
`this.addCardForm.reset()`

2023-02-01 03:48 UTC, ChamaraWee approved these changes

2023-02-01 03:49 UTC, merged