Add ngrx and hadle state
fcodelabs/training-web-angular pull request #45
Opened 2023-01-22 11:00 UTC by Nuwa-Hub

[ITP-1405]
[ITP-1401]

2023-01-25 03:18 UTC, ChamaraWee requested changes

2023-01-25 03:18 UTC, ChamaraWee commented on app/app/post-module/components/card-list/card-list.component.ts
> +    console.log(this.posts$);
remove logs

2023-01-25 03:18 UTC, ChamaraWee commented on app/app/post-module/components/card-list/card-list.component.scss
> +
wrong indentation

2023-01-25 03:19 UTC, ChamaraWee commented on src/app/components/card-form/card-form.component.ts
> +export class CardFormComponent implements OnInit {
run prettier

2023-01-25 03:20 UTC, ChamaraWee commented on src/app/containers/sign-in/sign-in.component.html
> +
spaces ?

2023-01-25 20:52 UTC, Nuwa-Hub commented on src/app/components/card-form/card-form.component.ts
> +export class CardFormComponent implements OnInit {
done

2023-01-25 20:52 UTC, Nuwa-Hub commented on app/app/post-module/components/card-list/card-list.component.scss
> +
done

2023-01-25 20:52 UTC, Nuwa-Hub commented on app/app/post-module/components/card-list/card-list.component.ts
> +    console.log(this.posts$);
done

2023-01-26 03:57 UTC, Nuwa-Hub commented on src/app/containers/sign-in/sign-in.component.html
> +
done

2023-02-01 06:04 UTC, Nuwa-Hub commented
done

2023-02-01 06:26 UTC, closed without merging